server.port=8080

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://chat_realtime_app_db:123@cluster0.kkj3n8a.mongodb.net/java_chat_app?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=java_chat_app
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.cache=false

app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:admin123}

logging.level.org.springframework.web.socket=INFO
logging.level.com.chat=INFO
